# Generated by Django 2.0.6 on 2018-12-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=800)),
                ('mobileNo', models.CharField(max_length=800)),
                ('city', models.CharField(max_length=800)),
                ('message', models.CharField(max_length=800)),
            ],
        ),
    ]
