# Generated by Django 2.0.6 on 2018-12-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingcart', '0003_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=200, unique=True)),
                ('zipCode', models.IntegerField()),
            ],
        ),
    ]
